<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StadiumsSystem</title>
</head>
<body>
    <div>Hello, user</div>
    <div><a href="/eventTypes">Перейти к списку видов мероприятий</a></div>
    <div><a href="/managers">Перейти к списку организаторов</a></div>
    <div><a href="/stadiums">Перейти к списку стадионов</a></div>
    <div><a href="/events">Перейти к списку мероприятий</a></div>
    <div><a href="/sectors">Перейти к списку секторов</a></div>
</body>
</html>